FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    zip unzip git curl libzip-dev

RUN docker-php-ext-install pdo pdo_mysql zip

COPY . /var/www/html/

WORKDIR /var/www/html

RUN curl -sS https://getcomposer.org/installer | php
RUN php composer.phar install

RUN a2enmod rewrite

EXPOSE 80